version: '3.4'
services:
  app:
    image: meteor-app:dev
    build:
      context: .
      target: dev
    command: meteor
    ports:
      - 3000:3000
    volumes:
      # - /app/node_modules
      - ./node_modules:/app/node_modules # (for vscode) to update run docker-compose run app npm install
      - /app/.meteor/local
      - ./:/app
    environment:
      - ROOT_URL=http://192.168.1.10
